# Generated by Django 5.1.6 on 2025-02-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin')], default='CLIENT', max_length=10),
        ),
    ]
