# Generated by Django 4.2.4 on 2025-02-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_make_stylist_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='stylist',
        ),
        migrations.RemoveField(
            model_name='service',
            name='stylists',
        ),
    ]
