# Generated by Django 5.1.6 on 2025-02-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_appointment_loyalty_points_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='purchaser',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='gift_card_used',
        ),
        migrations.RemoveField(
            model_name='review',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='client',
        ),
        migrations.RemoveField(
            model_name='review',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='review',
            name='stylist',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='services',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service_package',
        ),
        migrations.RemoveField(
            model_name='servicephoto',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='specialties',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='stylist',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='preferred_stylist',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='client',
        ),
        migrations.RemoveField(
            model_name='waitlistentry',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='loyalty_points_used',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reminder_sent',
        ),
        migrations.DeleteModel(
            name='FavoriteStylist',
        ),
        migrations.DeleteModel(
            name='GiftCard',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ServicePackage',
        ),
        migrations.DeleteModel(
            name='ServicePhoto',
        ),
        migrations.DeleteModel(
            name='Stylist',
        ),
        migrations.DeleteModel(
            name='WaitlistEntry',
        ),
    ]
