# Generated by Django 5.1.6 on 2025-03-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_time_slots'),
        ('accounts', '0016_alter_appointment_time_timeslot_and_more'),
    ]

    operations = [
    ]
